# Generated by Django 3.2.13 on 2023-05-17 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmovie',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 1), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
